apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: atreya
  MYSQL_USER: atreya
  MYSQL_PASSWORD: atreya
  MYSQL_DB_URL: mysql+pymysql://atreya:atreya@mysql-service:3306/seatmeup
